plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md

theme: jekyll-theme-cayman
description: [A simply and easy lab notebook website]
